"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type User = { id: number; username: string; email: string; role: "viewer" | "streamer" | "admin"; status: "active" | "banned"; created: string };
type Stats = { users: number; streamers: number; live_streams: number; open_reports: number };

export default function AdminPage() {
  const [role, setRole] = useState(""); const [users, setUsers] = useState<User[]>([]); const [stats, setStats] = useState<Stats | null>(null); const [notice, setNotice] = useState(""); const [ready, setReady] = useState(false);
  const token = typeof window === "undefined" ? "" : localStorage.getItem("eaststream_token") ?? ""; const auth = useMemo(() => ({ "Content-Type": "application/json", Authorization: `Bearer ${token}` }), [token]);
  const load = useCallback(async () => { try { const profile = await fetch("/api/profiles/me", { headers: auth }).then((r) => r.json()); setRole(profile.user?.role ?? ""); if (profile.user?.role !== "admin") return; const [overview, people] = await Promise.all([fetch("/api/admin/overview", { headers: auth }).then((r) => r.json()), fetch("/api/users", { headers: auth }).then((r) => r.json())]); setStats(overview.stats); setUsers(people.users ?? []); } catch { setNotice("Unable to load admin data."); } finally { setReady(true); } }, [auth]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function updateUser(id: number, body: object) { const path = "role" in body ? "role" : "status"; const response = await fetch(`/api/users/${id}/${path}`, { method: "PATCH", headers: auth, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) { setNotice(data.message || "Update failed."); return; } await load(); }
  async function addCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/categories", { method: "POST", headers: auth, body: JSON.stringify({ name: form.get("name"), slug: form.get("slug"), description: form.get("description") }) }); const data = await response.json(); setNotice(response.ok ? `Category “${data.category.name}” created.` : data.message || "Unable to create category."); if (response.ok) event.currentTarget.reset(); }
  if (!ready) return <main className="role-loading">Opening Admin Dashboard…</main>; if (!token || role !== "admin") return <AccessDenied title="Admin Dashboard" detail="This workspace is only available to Eaststream administrators." />;
  return <main className="role-shell"><DashboardHeader label="Admin Dashboard" /><div className="role-layout"><aside className="role-sidebar"><p>ADMIN TOOLS</p><a className="role-active" href="#overview">Overview</a><a href="#users">Users & roles</a><a href="#moderation">Moderation</a><a href="#categories">Categories</a><Link href="/">← Back to home</Link></aside><section className="role-content" id="overview"><p className="eyebrow purple"><span /> PLATFORM CONTROL</p><h1>Eaststream admin.</h1><p className="role-intro">Manage the safety and growth of your community.</p><div className="stat-grid">{[[stats?.users, "Users"], [stats?.streamers, "Streamers"], [stats?.live_streams, "Live now"], [stats?.open_reports, "Open reports"]].map(([value, label]) => <div className="stat-card" key={String(label)}><strong>{value ?? 0}</strong><span>{label}</span></div>)}</div><section className="role-card" id="users"><h2>Users & roles</h2><div className="user-table">{users.map((user) => <div className="user-row" key={user.id}><div><strong>{user.username}</strong><small>{user.email}</small></div><select value={user.role} onChange={(event) => void updateUser(user.id, { role: event.target.value })}><option value="viewer">Viewer</option><option value="streamer">Streamer</option><option value="admin">Admin</option></select><button className={user.status === "banned" ? "restore-button" : "ban-button"} onClick={() => void updateUser(user.id, { status: user.status === "banned" ? "active" : "banned" })}>{user.status === "banned" ? "Restore" : "Ban"}</button></div>)}</div></section><div className="dashboard-grid"><section className="role-card" id="moderation"><h2>Moderation queue</h2><p className="muted-note">{stats?.open_reports ?? 0} open reports. Reports will appear here for review and resolution.</p></section><section className="role-card" id="categories"><h2>Add a category</h2><form className="dashboard-form compact" onSubmit={addCategory}><input name="name" required placeholder="Category name" /><input name="slug" required placeholder="category-slug" pattern="[a-z0-9-]+" /><input name="description" placeholder="Short description" /><button className="primary-button">Add category</button></form></section></div>{notice && <p className="dashboard-notice">{notice}</p>}</section></div></main>;
}

function DashboardHeader({ label }: { label: string }) { return <header className="role-header"><Link className="brand" href="/"><span className="brand-mark">e</span><span>eaststream</span></Link><span>{label}</span><Link href="/">Member home ↗</Link></header>; }
function AccessDenied({ title, detail }: { title: string; detail: string }) { return <main className="access-denied"><span className="brand-mark">e</span><p className="eyebrow purple"><span /> ACCESS RESTRICTED</p><h1>{title}</h1><p>{detail}</p><Link className="primary-button" href="/">Back to home <span>→</span></Link></main>; }
