"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, BarChart3, Bell, ChevronDown, Eye, Home as HomeIcon, LayoutGrid, Plus, Radio, Search, User } from "lucide-react";

type Member = { id: number; username: string; email: string; role: "viewer" | "streamer" | "admin" };
type Profile = { display_name?: string; bio?: string; avatar_url?: string };
type LiveStream = { id: number; title: string; viewer_count: number; channel: { name: string; slug: string; category?: string } };
type Channel = { handle: string; name: string; title: string; game: string; viewers: string; symbol: string; color: string; accent: string };
type AuthMode = "sign-in" | "sign-up";
const colors = [["#1b2b5a", "#3a4f96"], ["#2e8b6f", "#3a4f96"], ["#9a7418", "#d8a93b"]] as const;

function getInitial(name: string) { return (name.match(/\p{L}/u)?.[0] ?? "•").toUpperCase(); }
function toChannel(stream: LiveStream, index: number): Channel {
  const [color, accent] = colors[index % colors.length];
  return { handle: stream.channel.slug, name: stream.channel.name, title: stream.title, game: stream.channel.category || "Live now", viewers: new Intl.NumberFormat("en", { notation: "compact" }).format(stream.viewer_count), symbol: getInitial(stream.channel.name), color, accent };
}
function authHeaders() { return { Authorization: `Bearer ${localStorage.getItem("eaststream_token") ?? ""}` }; }

export default function Home() {
  const [member, setMember] = useState<Member | null>(null);
  const [profile, setProfile] = useState<Profile>({});
  const [channels, setChannels] = useState<Channel[]>([]);
  const [streamsLoaded, setStreamsLoaded] = useState(false);
  const [authMode, setAuthMode] = useState<AuthMode | null>(null);

  useEffect(() => {
    const token = localStorage.getItem("eaststream_token");
    void fetch("/api/streams/live").then(async (r) => { if (!r.ok) throw new Error(); return r.json() as Promise<{ streams?: LiveStream[] }>; }).then((data) => setChannels((data.streams ?? []).map(toChannel))).catch(() => setChannels([])).finally(() => setStreamsLoaded(true));
    if (!token) return;
    void fetch("/api/profiles/me", { headers: authHeaders() }).then(async (r) => { if (!r.ok) throw new Error(); return r.json() as Promise<{ user: Member; profile?: Profile | null }>; }).then((data) => { setMember(data.user); setProfile(data.profile ?? {}); }).catch(() => localStorage.removeItem("eaststream_token"));
  }, []);

  if (member) return <MemberHome member={member} profile={profile} channels={channels} streamsLoaded={streamsLoaded} onProfileSaved={setProfile} onSignOut={() => { localStorage.removeItem("eaststream_token"); localStorage.removeItem("eaststream_username"); setMember(null); setProfile({}); }} />;
  return <main><div className="signal-field" />
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">e</span><span>eaststream</span></Link><nav className="nav-links" aria-label="Main navigation"><Link href="/discover">Live now</Link><Link href="/discover">Community</Link></nav><div className="nav-actions"><button className="text-button" onClick={() => setAuthMode("sign-in")}>Sign in</button><button className="primary-button small" onClick={() => setAuthMode("sign-up")}>Join Eaststream <span>→</span></button></div></header>
    <section className="hero"><div className="hero-copy"><p className="eyebrow"><span /> LIVE TOGETHER</p><h1>A home for the stories that <em>bring us closer.</em></h1><p className="hero-description">Watch live, find your community, and share what matters on Eaststream.</p><div className="hero-actions"><button className="primary-button" onClick={() => setAuthMode("sign-up")}>Join Eaststream <span>→</span></button><a className="watch-link" href="#live"><span className="play-icon">▶</span> Explore live streams</a></div><div className="hero-people"><div className="avatars"><i>A</i><i>K</i><i>M</i><i>+</i></div><span><strong>Join a growing community</strong><br />built around live moments.</span></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="sun" /><div className="mountain back" /><div className="mountain front" /><div className="stream-window"><div className="window-bar"><b /><b /><b /></div><div className="window-content"><span className="host">E</span><div><strong>Community live</strong><small>Stories from Eaststream</small></div><span className="live-pill">● LIVE</span></div></div><div className="comment comment-one"><span>✦</span> You&apos;re welcome here</div><div className="comment comment-two"><span>♥</span> Watching together</div></div></section>
    <section className="live-section" id="live"><div className="section-heading"><div><p className="eyebrow"><span /> DISCOVER</p><h2>Live right now</h2></div><Link className="view-all" href="/discover">Explore community <ArrowRight size={16} /></Link></div><LiveGrid channels={channels} streamsLoaded={streamsLoaded} /></section>
    <section className="community" id="community"><p className="eyebrow"><span /> YOUR SPACE</p><h2>Share your corner of the world.</h2><p>Create an account to follow creators, join chats, and start your own channel when you&apos;re ready.</p><button className="primary-button" onClick={() => setAuthMode("sign-up")}>Create your account <span>→</span></button></section><footer><span>© {new Date().getFullYear()} Eaststream</span><div><a href="#community">Community guidelines</a><a href="#live">Discover</a></div></footer>
    {authMode && <AuthModal mode={authMode} onClose={() => setAuthMode(null)} onModeChange={setAuthMode} onAuthenticated={(nextMember, nextProfile) => { setMember(nextMember); setProfile(nextProfile); setAuthMode(null); }} />}
  </main>;
}

function ChannelCard({ channel }: { channel: Channel }) { return <><div className="channel-visual" style={{ background: `linear-gradient(135deg, ${channel.color}, ${channel.accent})` }}><span className="live-pill">● LIVE</span><span className="viewer-pill"><Eye size={12} /> {channel.viewers}</span><div className="visual-symbol">{channel.symbol}</div><div className="visual-lines" /></div><div className="channel-info"><div className="channel-avatar" style={{ background: channel.color }}>{channel.symbol}</div><div><h3>{channel.name}</h3><p>{channel.title}</p><span>{channel.game}</span></div></div></>; }
function LiveGrid({ channels, streamsLoaded }: { channels: Channel[]; streamsLoaded: boolean }) { return <div className="channel-grid">{channels.map((channel) => <Link className="channel-card" href={`/stream/${encodeURIComponent(channel.handle)}`} key={channel.handle}><ChannelCard channel={channel} /></Link>)}{streamsLoaded && !channels.length && <div className="empty-state">No streams are live right now. Check back soon.</div>}</div>; }

function AuthModal({ mode, onClose, onModeChange, onAuthenticated }: { mode: AuthMode; onClose: () => void; onModeChange: (mode: AuthMode) => void; onAuthenticated: (member: Member, profile: Profile) => void }) {
  const [notice, setNotice] = useState(""); const [submitting, setSubmitting] = useState(false); const isSignUp = mode === "sign-up";
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setNotice(""); const form = new FormData(event.currentTarget); const response = await fetch(isSignUp ? "/api/auth/register" : "/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(isSignUp ? { username: form.get("username"), email: form.get("email"), password: form.get("password") } : { email: form.get("email"), password: form.get("password") }) }); const data = await response.json().catch(() => null); if (!response.ok) { setNotice(data?.message || "Unable to continue."); setSubmitting(false); return; } if (isSignUp) { onModeChange("sign-in"); setNotice("Account created. Sign in to continue."); setSubmitting(false); return; } localStorage.setItem("eaststream_token", data.token); const profileResponse = await fetch("/api/profiles/me", { headers: { Authorization: `Bearer ${data.token}` } }); const profileData = await profileResponse.json().catch(() => null); const signedInMember = profileData?.user ?? data.user; localStorage.setItem("eaststream_username", signedInMember.username); onAuthenticated(signedInMember, profileData?.profile ?? {}); }
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="auth-modal" role="dialog" aria-modal="true" aria-labelledby="auth-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose} aria-label="Close">×</button><span className="brand-mark modal-mark">e</span><p className="eyebrow purple"><span /> WELCOME</p><h2 id="auth-title">{isSignUp ? "Join Eaststream" : "Welcome back"}</h2><p className="modal-description">{isSignUp ? "Create your account and find your community." : "Sign in to continue watching together."}</p><form onSubmit={submit}>{isSignUp && <label>Username<input required name="username" autoComplete="username" /></label>}<label>Email<input required name="email" type="email" autoComplete="email" /></label><label>Password<input required name="password" type="password" minLength={8} autoComplete={isSignUp ? "new-password" : "current-password"} /></label>{notice && <p className="form-notice">{notice}</p>}<button className="primary-button auth-submit" disabled={submitting}>{submitting ? "Please wait…" : isSignUp ? "Create account" : "Sign in"} <span>→</span></button></form><p className="switch-auth">{isSignUp ? "Already have an account?" : "New to Eaststream?"} <button onClick={() => { setNotice(""); onModeChange(isSignUp ? "sign-in" : "sign-up"); }}>{isSignUp ? "Sign in" : "Create one"}</button></p></section></div>;
}

function MemberHome({ member, profile, channels, streamsLoaded, onProfileSaved, onSignOut }: { member: Member; profile: Profile; channels: Channel[]; streamsLoaded: boolean; onProfileSaved: (profile: Profile) => void; onSignOut: () => void }) {
  const router = useRouter(); const [editingProfile, setEditingProfile] = useState(false); const [studioOpen, setStudioOpen] = useState(false); const [saving, setSaving] = useState(false); const [profileError, setProfileError] = useState(""); const displayName = profile.display_name || member.username; const initial = getInitial(displayName); const isCreator = member.role !== "viewer";
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setProfileError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/profiles/me", { method: "PATCH", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ display_name: form.get("display_name"), bio: form.get("bio"), avatar_url: form.get("avatar_url") }) }); const data = await response.json().catch(() => null); if (response.ok) { onProfileSaved(data.profile); setEditingProfile(false); } else setProfileError(data?.message || "Unable to update your profile."); setSaving(false); }
  return <main className="member-shell">
    <header className="member-topbar"><Link className="brand" href="/"><span className="brand-mark">e</span><span>eaststream</span></Link><form className="member-search" onSubmit={(event) => { event.preventDefault(); const query = String(new FormData(event.currentTarget).get("q") ?? "").trim(); router.push(`/discover${query ? `?q=${encodeURIComponent(query)}` : ""}`); }}><Search size={16} /><label className="sr-only" htmlFor="member-search-input">Search streams, creators, and categories</label><input id="member-search-input" name="q" placeholder="Search streams, creators, and categories" /></form><div className="member-actions"><button className="create-button" onClick={() => isCreator ? router.push("/studio") : setStudioOpen(true)}><Plus size={16} /> Create</button><Link className="notification-button" href="/discover?following=1" aria-label="See live channels you follow" title="Live channels you follow"><Bell size={18} /></Link><button className="member-menu" onClick={() => setEditingProfile(true)}><span className="member-avatar">{initial}</span><span>{displayName}</span><ChevronDown size={16} /></button></div></header>
    <div className="member-layout"><aside className="member-sidebar"><p className="sidebar-label">YOUR SPACE</p><a className="side-link active" href="#home"><HomeIcon size={18} /><span>Home</span></a><Link className="side-link" href="/discover"><Radio size={18} /><span>Live now</span></Link><Link className="side-link" href="/discover"><LayoutGrid size={18} /><span>Browse</span></Link><Link className="side-link" href="/discover?following=1"><Bell size={18} /><span>Following</span></Link><button className="side-link side-button" onClick={() => setEditingProfile(true)}><User size={18} /><span>My profile</span></button>{isCreator && <><p className="sidebar-label space">CREATOR</p><Link className="side-link" href="/studio"><Radio size={18} /><span>Go live</span></Link><Link className="side-link" href="/studio/analytics"><BarChart3 size={18} /><span>Analytics</span></Link></>}<div className="sidebar-bottom"><div className="sidebar-profile"><span className="member-avatar large">{initial}</span><div><strong>{displayName}</strong><small>@{member.username}</small></div></div><button onClick={onSignOut}>Sign out</button></div></aside>
      <section className="member-content" id="home"><section className="member-hero"><div className="member-hero-copy"><p className="eyebrow"><span /> WELCOME BACK</p><h1>Good to see you,<br /><em>{displayName.split(" ")[0]}.</em></h1><p>{channels.length ? `${channels.length} ${channels.length === 1 ? "stream is" : "streams are"} live in your community right now.` : "Your community is waiting for its next live moment."}</p><a className="hero-dashboard-action" href="#live">Explore live <ArrowRight size={16} /></a></div><div className="member-hero-orb"><span>{initial}</span><small>{isCreator ? "Creator" : "Community member"}</small></div></section><div className="member-section-title" id="live"><div><p className="eyebrow"><span /> DISCOVER</p><h2>Live right now</h2><p>Find a conversation worth joining.</p></div><a className="view-all" href="#browse">Browse all <ArrowRight size={14} /></a></div><div className="member-channel-grid" id="browse">{channels.map((channel, index) => <Link className={index === 0 && channels.length > 2 ? "channel-card featured" : "channel-card"} href={`/stream/${encodeURIComponent(channel.handle)}`} key={channel.handle}><ChannelCard channel={channel} /></Link>)}{streamsLoaded && !channels.length && <div className="member-empty"><Radio size={28} /><h3>Nothing is live right now.</h3><p>Check back soon, or start a channel and create the next live moment.</p>{!isCreator && <button className="primary-button small" onClick={() => setStudioOpen(true)}>Create a channel <span>→</span></button>}{isCreator && <Link className="primary-button small" href="/studio">Go live <span>→</span></Link>}</div>}</div></section></div>
    {editingProfile && <div className="modal-backdrop" role="presentation" onMouseDown={() => setEditingProfile(false)}><section className="auth-modal profile-modal" role="dialog" aria-modal="true" aria-labelledby="profile-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-button" onClick={() => setEditingProfile(false)} aria-label="Close">×</button><span className="member-avatar profile-avatar">{initial}</span><p className="eyebrow purple"><span /> YOUR PROFILE</p><h2 id="profile-title">Make it yours</h2><p className="modal-description">This is how your community sees you.</p><form onSubmit={saveProfile}><label>Display name<input required name="display_name" defaultValue={displayName} /></label><label>Bio<textarea name="bio" defaultValue={profile.bio ?? ""} placeholder="Tell people a little about yourself" /></label><label>Profile photo URL<input type="url" name="avatar_url" defaultValue={profile.avatar_url ?? ""} placeholder="https://…" /></label>{profileError && <p className="form-notice">{profileError}</p>}<button className="primary-button auth-submit" disabled={saving}>{saving ? "Saving…" : "Save profile"} <span>→</span></button></form></section></div>}{studioOpen && <CreatorStudio member={member} onClose={() => setStudioOpen(false)} />}
  </main>;
}

function CreatorStudio({ member, onClose }: { member: Member; onClose: () => void }) {
  const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  async function createChannel(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setNotice(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/channels/me", { method: "POST", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ name: form.get("name"), description: form.get("description") }) }); const data = await response.json().catch(() => null); setNotice(response.ok ? "Your channel is ready. Open Creator Studio to go live." : data?.message || "Unable to create your channel."); setSaving(false); }
  return <div className="modal-backdrop studio-backdrop" role="presentation" onMouseDown={onClose}><section className="studio-modal" role="dialog" aria-modal="true" aria-labelledby="studio-title" onMouseDown={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose} aria-label="Close">×</button><p className="eyebrow purple"><span /> CREATOR TOOLS</p><h2 id="studio-title">Start your channel</h2><p className="modal-description">Set up your space, then open Creator Studio when you are ready to broadcast.</p><form className="studio-form" onSubmit={createChannel}><label>Channel name<input required name="name" defaultValue={`${member.username}'s channel`} /></label><label>About your channel<textarea name="description" placeholder="What will you share with your community?" /></label>{notice && <p className="form-notice">{notice}</p>}<button className="primary-button" disabled={saving}>{saving ? "Creating…" : "Create channel"} <span>→</span></button></form><div className="studio-channel"><span className="member-avatar">{getInitial(member.username)}</span><div><strong>Already a creator?</strong><small>Open your broadcasting tools.</small></div><Link href="/studio">Studio</Link></div></section></div>;
}
