"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Analytics = { channel: { name: string; slug: string; category?: string; is_live: boolean }; metrics: { followers: number; broadcasts: number; live_viewers: number; peak_viewers: number; total_live_seconds: number }; recent_streams: { id: number; title: string; status: string; viewer_count: number; started_at?: string; duration_seconds: number }[]; note: string };

function formatDuration(seconds: number) { const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); return hours ? `${hours}h ${minutes}m` : `${minutes}m`; }

export default function AnalyticsPage() {
  const [data, setData] = useState<Analytics | null>(null); const [error, setError] = useState(""); const [ready, setReady] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { void (async () => { try { const response = await fetch("/api/creator/analytics", { headers: { Authorization: `Bearer ${localStorage.getItem("eaststream_token")}` } }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Unable to load analytics."); setData(result); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load analytics."); } finally { setReady(true); } })(); }, 0); return () => window.clearTimeout(timer); }, []);
  if (!ready) return <main className="role-loading">Loading your channel data…</main>;
  if (error || !data) return <main className="access-denied"><span className="brand-mark">e</span><p className="eyebrow purple"><span /> CREATOR ANALYTICS</p><h1>Analytics unavailable</h1><p>{error || "Create a channel before viewing your analytics."}</p><Link className="primary-button" href="/studio">Open Creator Studio <span>→</span></Link></main>;
  const statCards = [[data.metrics.live_viewers, "Watching now", data.channel.is_live ? "Live audience" : "Go live to see this update", "cyan"], [data.metrics.followers, "Total followers", "People who chose your channel", "violet"], [formatDuration(data.metrics.total_live_seconds), "Time live", "Across completed and current broadcasts", "gold"], [data.metrics.peak_viewers, "Peak viewers", "Best audience across broadcasts", "coral"]];
  return <main className="role-shell analytics-shell"><header className="role-header"><Link className="brand" href="/"><span className="brand-mark">e</span><span>eaststream</span></Link><span>Creator analytics</span><Link href="/studio">Creator Studio ↗</Link></header><div className="role-layout"><aside className="role-sidebar"><p>CREATOR TOOLS</p><Link href="/studio">Broadcast</Link><a className="role-active" href="#overview">Analytics</a><a href="#history">Stream history</a><Link href="/">← Back to home</Link></aside><section className="role-content" id="overview"><div className="analytics-hero"><div><p className="eyebrow purple"><span /> CHANNEL INTELLIGENCE</p><h1>{data.channel.name}<br /><em>at a glance.</em></h1><p>{data.channel.category || "Your channel"} · <span className={data.channel.is_live ? "analytics-live" : ""}>{data.channel.is_live ? "● Live now" : "Offline"}</span></p></div><div className="analytics-orb"><span>✦</span><strong>{data.metrics.followers}</strong><small>followers</small></div></div><div className="analytics-stat-grid">{statCards.map(([value, label, detail, tone]) => <article className={`analytics-stat ${tone}`} key={String(label)}><span className="metric-glyph">◌</span><strong>{value}</strong><h2>{label}</h2><p>{detail}</p></article>)}</div><section className="role-card analytics-chart"><div className="chart-heading"><div><h2>Audience momentum</h2><p>Viewer signals across your recent broadcasts</p></div><span>Last 10 streams</span></div><div className="bar-chart">{data.recent_streams.length ? data.recent_streams.slice().reverse().map((stream, index) => <div className="chart-column" key={stream.id}><span style={{ height: `${Math.max(8, Math.min(100, stream.viewer_count || (index + 1) * 8))}%` }} /><small>{stream.viewer_count}</small></div>) : <div className="chart-empty">Your audience chart will appear after your first broadcast.</div>}</div></section><section className="role-card" id="history"><div className="chart-heading"><div><h2>Recent broadcasts</h2><p>{data.metrics.broadcasts} broadcasts created</p></div><Link href="/studio">Go live →</Link></div><div className="broadcast-list">{data.recent_streams.length ? data.recent_streams.map((stream) => <article key={stream.id}><span className={stream.status === "live" ? "broadcast-dot live-dot" : "broadcast-dot"} /><div><strong>{stream.title}</strong><small>{stream.started_at ? `${new Date(stream.started_at).toLocaleDateString()} · ${formatDuration(stream.duration_seconds)}` : "Not started"}</small></div><span className="broadcast-status">{stream.status}</span><b>◉ {stream.viewer_count}</b></article>) : <p className="muted-note">No broadcasts yet. Start your first stream from Creator Studio.</p>}</div></section><p className="analytics-note">✦ {data.note}</p></section></div></main>;
}
